### ISSUE TITLE
Migrate build from Travis to Github Actions

### ISSUE THREAD

**Issue by tpietzsch** [mastodon-sc/mastodon-collection#10]

**Comment by tinevez** [comment]
See https://github.com/mastodon-sc/mastodon/pull/149 for inspiration.
Tobias, who do you want to take care of this?

**Comment by ctrueden** [comment]
I submitted PRs switching to GitHub Actions for the following repositories:

* mastodon-collection
* mastodon-ellipsoid-fitting
* mastodon-graph
* mastodon-pasteur
* mastodon-selection-creator
* mastodon-tomancak
* mastodon-tracking

**Comment by tinevez** [comment]
Merged all of them.
Thanks!

**Comment by ctrueden** [comment]
mastodon-sc/mastodon-tomancak#5 is still open.
